[package]
name = "calcit_std"
version = "0.2.11"
authors = ["jiyinyiyong <jiyinyiyong@gmail.com>"]
edition = "2024"


[lib]
name = "calcit_std"
path = "src/lib.rs"
crate-type = ["dylib"] # Creates dynamic lib


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.149"
chrono = "0.4.44"
cirru_edn = "0.7.7"
cirru_parser = "0.2.8"
nanoid = "0.4.0"
rand = "0.8.5"
ctrlc = "3.5.2"
md5 = "0.7.0"
walkdir = "2.5.0"
glob = "0.3.3"

# [profile.release]
# lto = true
# codegen-units = 1
# opt-level = "z"  # Optimize for size.
