[package]
name = "calcit_std"
version = "0.0.4"
authors = ["jiyinyiyong <jiyinyiyong@gmail.com>"]
edition = "2018"

[lib]
name = "calcit_std"
path = "src/lib.rs"
crate-type = ["dylib"] # Creates dynamic lib


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
chrono = "0.4.19"
regex = "1.5.4"
cirru_edn = "0.1.12"
cirru_parser = "0.1.8"
nanoid = "0.4.0"
rand = "0.8.4"
ctrlc = "3.2.1"
