on:
  push:
    branches:
      - master
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy

      - uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/calcit-lang/calcit/releases/download/0.8.28/cr"
          name: "cr"
          version: "0.8.28"

      - uses: supplypike/setup-bin@v3
        with:
          uri: "https://github.com/calcit-lang/calcit/releases/download/0.8.28/caps"
          name: "caps"
          version: "0.8.28"

      - run: cargo build --release

      - run: mkdir dylibs/ && ls target/release/ && cp -v target/release/libcalcit_std.* dylibs/

      - run: cr -1
